### ISSUE TITLE
Question on Solar / Wind Generation Figures & Sources

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#128]
Got a response from a local environmental activist in my neighborhood:

> Actually, Illinois has over 7,000 MW of windpower and over 1,000 MW of solar at present, but we need a combo of over 1,000 MW/year to go electric, preferably 2,000 . Having gigawatt-hours of energy storage, starting with 4-8-12 hour blocks, will also be necessary.
> 
> Illinois is at an interesting topping point, getting past 10% of electricity generation from renewable energy sources.

Our figures are quite different than that: 

![Screen Shot 2022-07-18 at 8 23 44 AM](https://user-images.githubusercontent.com/919583/179521100-ea7f24ed-1e2c-4d44-a23d-6deb7b8d2c80.png)

I asked for their data source and will report back if they share one we can use. It would be good to document and share (as I think @swatland610 suggested) our methodology, especially for this calculation.

**Comment by swatland610** [comment]
@derekeder yikes! a little depressing start data wise, but I'm loving that we are getting questions and feedback on it! 

Here are my thoughts ( & my own steps for troubleshooting this right now): 

1. Just gut checking our EIA data, I'm noticing one slight oversight on my part. Where it says `since Illinois has XX MWs etc...` that's actually showing the actual output - not the capacity. So I need to divide the output back by the capacity factor to get the actual `capacity`. 

So gut checking that - I actually get **1000 MWs** of solar (yay!) but only **4,600MWs** of wind (boo!). 

So maybe there's a better data source for at least the Wind portion of this! 

Also, the PJM GATS data they shared is awesome! I can organize that and better compare numbers. It's just essentially a drilled down view of every solar and/or wind farm with their nameplate capacity - which we've just needed to estimate. (Possibly part of the problem). 

2. I can wrap up the process doc for how we did this, but admittedly, I'm wondering if it would be also helpful to chat directly with your contact. As I'm definitely not going to claim to be an expert in this, it sounds like your contact is definitely more knowledgable! 

How would you feel about me setting up a 30 - 45 minute chat with your contact about how they've projected Illinois's needs? 

Regardless of yes or no, I'll finish up my high level `how we calculated this` doc to share.

**Comment by swatland610** [comment]
Reached out to Mark but he has not followed back up about setting a time to discuss our process for calculating this.
