### ISSUE TITLE
Clarify Missing Emissions Data for 2019-2022 in Area Chart

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#129]
There's a gap between 2018 and 2022 in our area chart:
![Screen Shot 2022-07-19 at 7 56 34 PM](https://user-images.githubusercontent.com/919583/179872805-9712cd36-f184-4474-9f15-78abd2d27755.png)

Option 1: find state totals for the missing years and fill them i9n

Option 2: show greyed out estimate section for the missing years

**Comment by hkier** [comment]
I understand there will always be a lag between the current year and the latest year available data.  There are basically two ways to solve this problem when filling in the missing years.

1. Take the last year for which we have data and then keep it constant until the current year at which point we will show a reduction in emissions.  This will result in a couple of years with a straight line for emissions which we can indicate as estimated/unknown.  The color for this area would differ from the other areas.
2. Instead of starting the reduction at the current year, we can assume the reductions started the year after the last data point.  In this case, the graph would appear the same as it does today, except the missing years would be shown.  However, those years would be considered "projected" rather than any estimate.

Which approach do we want to take with the "missing" years?
