### ISSUE TITLE
Cite Source Author and Month/Year for Data Visualizations

### ISSUE THREAD

**Issue by derekeder** [chihacknight/decarbonize-my-state#132]
One thing I really like about the SpeedandScale.com website is how they cite their statistics:
![Screen Shot 2022-07-25 at 9 33 43 PM](https://user-images.githubusercontent.com/919583/180910563-91c4956d-d796-4f45-a6ca-3c36be915be0.png)

I think we should do something similar and show the source and month/year for each data source, including:

- Home page: map of emissions by state (WRI, 2018)
- State detail
 -  Emissions over time (WRI, 2018)
 - CO2 Equivalent Emissions in Illinois by Source (WRI, 2018)
 - Building Systems Electrified (Microsoft Maps, Mar 2021; NREL, Dec 2021)
 - Vehicles Electrified (US DOT, Feb 2021)
 - Power Plants (EPA, Jan 2021)

**Comment by vkoves** [comment]
@charunupara said he can take this on

**Comment by charunupara** [comment]
@vkoves @derekeder starting to work on this, but wanted to ask for some opinions on how to do this properly since I'm new to both the project and React/Gatsby. 

I was thinking a good way to do it is to create a `data-sources` dictionary along with a React component that renders the data source name and date in a similar way to the SpeedAndScale citation Derek shared. Thought it was a good idea to have a clear source of truth for data sources that we can pull from instead of inserting those directly onto each page. I'm just unsure of where the potential dictionary would go, and wanted to see if this would even be a good path to go down.

Let me know what you guys think!

**Comment by vkoves** [comment]
@charunupara - I love that! I think you could add a `constants.ts` or `data-dictionary.ts` and then move the about page to use that. I think the constant might be an object keyed on an enum, like so:

```ts
enum DataKeys {
  EmissionsMap: 'em-map',
  ...
};

const dataDictionary = {
  DataKeys.EmissionsMap: {
    source: 'EPA',
    yearUpdated: '2020',
  }
  ...
}
```

I think a component to render the title and stuff would be fine, but isn't a necessity. But I think it would be useful. If the enum proves difficult you could also just use strings, but that could be messier.

**Comment by charunupara** [comment]
Yep, using the same source for in-place citations and the About page is exactly why I thought having a dictionary would be helpful. And keying by enums sounds like a good idea. Wasn't sure how to structure the object earlier but this is super helpful, thanks @vkoves!

**Comment by vkoves** [comment]
@charunupara - wanted to follow up on this, are you still tackling this one?
