### ISSUE TITLE
Twitter Card Is Unhappy

### ISSUE THREAD

**Issue by nofurtherinformation** [chihacknight/decarbonize-my-state#96]
Other social cards seem OK, but we're failing twitter's validator:
![image](https://user-images.githubusercontent.com/10041771/168936279-cfcc8eb0-fe76-4376-a114-6516c4fa8fed.png)

**Comment by vkoves** [comment]
@derekeder and @nofurtherinformation - since there's 50 states I wonder if it would be worth doing social card images dynamically so we could show something like the state breakdown. I could make a quick basic social image for the site, but I think making it dynamic would be cool and prevent it going out of date. This article has some methods specifically for doing this with Gatsby: https://posthog.com/blog/dynamic-open-graph-images

This CSS tricks article also has some resources: https://css-tricks.com/auto-generated-social-media-images/

Here's a quick concept I made for what I'm thinking, though this is likely out of scope of the MVP:

![Social Card 1](https://user-images.githubusercontent.com/3187531/169719088-5299da68-2b33-4f69-828f-5be63474abf5.png)

**Comment by herrerarobert** [comment]
Fix for this has been merged into main branch.
